<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'fin1te\\SafeCurl' => array($vendorDir . '/fin1te/safecurl/src'),
);
