<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit66a63903e06f0555af701f86412cdd2c
{
    public static $prefixesPsr0 = array (
        'f' => 
        array (
            'fin1te\\SafeCurl' => 
            array (
                0 => __DIR__ . '/..' . '/fin1te/safecurl/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit66a63903e06f0555af701f86412cdd2c::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
